[programs.devnet]
be = "E1scYKZaENP8SN1WPwpsQnX3eFA8zwbzgYg1tQ8RxTvN"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/luke/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
# test = "ts-node ./tests/be.ts"
